import 'package:al_quran/design_system/foundations/colors/app_colors.dart';
import 'package:al_quran/design_system/foundations/typography/text_styles.dart';
import 'package:flutter/material.dart';

final ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  useMaterial3: true,
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: DarkColors.primary,
    onPrimary: DarkColors.onPrimary,
    primaryContainer: DarkColors.primaryContainer,
    onPrimaryContainer: DarkColors.onPrimaryContainer,
    secondary: DarkColors.secondary,
    onSecondary: DarkColors.onSecondary,
    secondaryContainer: DarkColors.secondaryContainer,
    onSecondaryContainer: DarkColors.onSecondaryContainer,
    tertiary: DarkColors.tertiary,
    onTertiary: DarkColors.onTertiary,
    tertiaryContainer: DarkColors.tertiaryContainer,
    onTertiaryContainer: DarkColors.onTertiaryContainer,
    background: DarkColors.background,
    onBackground: DarkColors.onBackground,
    surface: DarkColors.surface,
    onSurface: DarkColors.onSurface,
    surfaceVariant: DarkColors.surfaceVariant,
    onSurfaceVariant: DarkColors.onSurfaceVariant,
    outline: DarkColors.outline,
    error: Colors.red,
    onError: Colors.white,
    errorContainer: Colors.redAccent,
    onErrorContainer: Colors.white,
    scrim: DarkColors.scrim,
    shadow: DarkColors.shadow,
    inverseSurface: Colors.white12,
    onInverseSurface: Colors.black87,
    inversePrimary: DarkColors.primary,
    surfaceTint: DarkColors.primary,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyles.displayLarge,
    displayMedium: TextStyles.displayMedium,
    displaySmall: TextStyles.displaySmall,
    headlineLarge: TextStyles.headlineLarge,
    headlineMedium: TextStyles.headlineMedium,
    headlineSmall: TextStyles.headlineSmall,
    titleLarge: TextStyles.titleLarge,
    titleMedium: TextStyles.titleMedium,
    titleSmall: TextStyles.titleSmall,
    bodyLarge: TextStyles.bodyLarge,
    bodyMedium: TextStyles.bodyMedium,
    bodySmall: TextStyles.bodySmall,
    labelLarge: TextStyles.labelLarge,
    labelMedium: TextStyles.labelMedium,
    labelSmall: TextStyles.labelSmall,
  ),
  fontFamily: 'Poppins',
  iconButtonTheme: IconButtonThemeData(style: ButtonStyle()),
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    backgroundColor: DarkColors.surface, // or any color you prefer
    selectedItemColor: DarkColors.primary,
    unselectedItemColor: DarkColors.onSurface.withValues(alpha: 0.6),
    selectedLabelStyle: TextStyles.labelSmall,
    unselectedLabelStyle: TextStyles.labelSmall,
    showSelectedLabels: true,
    showUnselectedLabels: true,
    type: BottomNavigationBarType.fixed, // or .shifting
  ),
);
